### ISSUE TITLE
Define which versions are searchable, and manage it through the Algolia configuration and the UI

### ISSUE THREAD

**Issue by alachambre** [bonitasoft/bonitasoft.github.io#116]
Algolia provides us freely our search service because we are an open source company. 
We do not want to abuse it by indexing unnecessary pages.

-> We think that old Bonita versions should not be indexed (i.e it won't be possible to use the search in the documentation of those versions). Those versions are used by only few peoples, and the amount of index produced by those versions is considerable. 

So our proposal is to define a relation between the latest supported Bonita version and the latest indexed version. 
Each time a new Bonita version is out, the oldest searchable version will be removed and so on.

We also need to manage this searchable state from the UI. We could simply hide the search for not searchable versions. The state `searchable` can probably be defined in the Antora configuration of the related version (branch).

**Comment by NathalieC** [comment]
@alachambre what do you mean by "those versions are only used by few people"? 
Here are the figures, and the reason why we are talking about 7.5 and above, and not the supported versions (7.9 and above):

Total pour 5.6.0 - 1
Total pour 5.9.0 - 3
Total pour 5.10.0 - 6
Total pour 5.10.2 - 1

Total pour 6.2.0 - 2
Total pour 6.3.0 - 2
Total pour 6.4.0 - 1
Total pour 6.5.0 - 2

Total pour 7.1.0 - 5
Total pour 7.2.0 - 3
Total pour 7.3.0 - 4
Total pour 7.4.0 - 4
Total pour 7.5.0 - 10
Total pour 7.5.2 - 1
Total pour 7.6.0 - 6
Total pour 7.6.2 - 3
Total pour 7.7.0 - 14
Total pour 7.7.2- 4
Total pour 7.8.0 - 15
Total pour 7.8.2 - 10
Total pour 7.9.0 - 8
Total pour 7.9.2 - 9
Total pour 7.10.0 - 20
Total pour 7.11.0 - 7
Total pour 7.10.2 -16
Total pour 7.11.2 -14
Total pour 7.12.2 - 1

Total pour Unknown - 4

**Comment by NathalieC** [comment]
What we would also need to know is how much the doc changes from one version to another.
Another way work by "diff" between one version and another.
I'm not sure about how, but throwing this idea in case one of you catches it to do something with it.

**Comment by tbouffard** [comment]
Current idea for Bonita Platform:
> given the latest supported version, let allow to search on four previous versions

So for now
- latest officially supported version: 7.9
- latest searchable version: 7.5

**Comment by tbouffard** [comment]
All versions in the documentation will be searchable. We will have a process to archive old documentation when a new one is released
