### ISSUE TITLE
Change page title (browser tab)

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#119]
Hello, 

For SEO purposes and to clarify things for the visitor, please rename the page title from "Bonita Documentation :: Bonita Documentation" to "Bonita Documentation | Bonitasoft"
![image](https://user-images.githubusercontent.com/52718045/108792503-45859c00-7536-11eb-92a0-3d14a07c2891.png)

Thanks

**Comment by alachambre** [comment]
Oops ^^'

**Comment by tbouffard** [comment]
The page title is currently built by the UI Bundle using the `<page_title> :: <site_title>` form.
For instance
- https://bonitasoft.github.io/cloud/latest/FAQ: `Frequently Asked Questions :: Bonita Documentation`
- https://bonitasoft.github.io/bcd/3.4/upgrade_bcd: `Migrate from an earlier version of BCD :: Bonita Documentation`

I guess this page title generation comes from the Antora Default UI: https://antora.gitlab.io/antora-ui-default/index.html


The issue described here only occurs on the Bonita Platform index pages, so changing the title of the pages in the documentation content repository (bonita-doc) will fix the issue (all branches/versions).
The page title is currently `Bonita Documentation`; in other components we have something correct and the Bonita Plateform part of the documentation does not follow the same convention (this is an additional reason to change the titles)
- bici: `Bonita Intelligent Continuous Improvement Add-on`
- bcd: `Bonita Continuous Delivery Add-on`
- cloud: `Bonita Cloud`

I don't agree with proposal of putting `| Bonitasoft` at the end of each title, this is overwhelming and don't bring anything for the end user.
Something related to the `Bonita Documentation` has more sense, or `Bonita` alone.
About the separator, it is currently `::` which is quite uncommon, most of the time, sites use `-`

**Comment by LBALP** [comment]
@tbouffard If I may insist on adding Bonitasoft at the end, I don't think it's overwhelming as we usually don't see more than 30 characters if only one tab open (which is rare) and it is pretty common to use the "|" as separator so it looks nice in the search results. This is purely for SEO purposes that I'm requesting that. 

But you're right, more pages are concerned and considering that they have long names for 2 of them I would suggest as page titles:
- Bonita | Bonitasoft Documentation 
- Bonita Intelligent Continuous Improvement Add-on | Bonitasoft Documentation 
- Bonita Continuous Delivery Add-on | Bonitasoft Documentation 
- Bonita Cloud | Bonitasoft Documentation 

Of course the "| Bonitasoft Documentation" won't show up on the page itself, only on the tab.

You can also shorten it by using BICI Add-on OR BCD Add-on or using Docs instead of Documentation.
I let you pick what you prefer.
Thanks :)
