### ISSUE TITLE
Change blue for both header and footer

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#120]
Please use this blue **#19465F** for both footer and header in order to keep up with the style guidelines 
![image](https://user-images.githubusercontent.com/52718045/108792886-2a675c00-7537-11eb-99be-e8685a3c2cba.png)

Use this blue as well on the text when you hover a card

**Comment by tbouffard** [comment]
@LBALP what is the motivation for this? stick more to the Bonitasoft website design?
I guess this is for the same reasons as in #121
