### ISSUE TITLE
Bonitasoft logo in white instead of grey-ish

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#124]
![image](https://user-images.githubusercontent.com/52718045/108793840-5c79bd80-7539-11eb-87eb-de07fef7143c.png)

**Comment by alachambre** [comment]
This Logo is clickable, when you hover it with the mouse it became pure white to give a feedback to the User, it is consistent with the whole toolbar. 
We can think of an other behavior if you think it's absolutely not ok.

**Comment by LBALP** [comment]
As discussed it's not necessary, let's change it to pure white, thanks
