### ISSUE TITLE
Add caps at the beginning of each section of the left Menu 

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#125]
Example for the REST API section, not all the words have caps
![image](https://user-images.githubusercontent.com/52718045/108793955-a82c6700-7539-11eb-9e73-52185f6533ea.png)

**Comment by alachambre** [comment]
Hello, 

I agree, all menu should start with a caps. 
However, it is a matter of documentation content and not documentation site. 
It has to be fixed in this file , for each version -> https://github.com/bonitasoft/bonita-doc/blob/7.12/md/taxonomy.md

**Comment by benjaminParisel** [comment]
Done in https://github.com/bonitasoft/bonita-doc/commit/4fef1b15792587856720f899c094c944d92761c4
