### ISSUE TITLE
Add red #DD042B

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#126]
Please, color in red **#DD042B** clickable sections like the cards (will look less white if the background is in 50% opacity red) 
![image](https://user-images.githubusercontent.com/52718045/108794277-4ddfd600-753a-11eb-89a7-37275641a4f2.png)

Without opacity, color in red the links to the content of the page : 
![image](https://user-images.githubusercontent.com/52718045/108794437-97302580-753a-11eb-95d8-5ae9137b3281.png)

**Comment by tbouffard** [comment]
@LBALP what is the motivation for this? stick more to the Bonitasoft website design?
I guess this is for the same reasons as in #121
