### ISSUE TITLE
Red button to select Bonita version

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#127]
The same way as the Download button on the corp website home page 
![image](https://user-images.githubusercontent.com/52718045/108795324-20475c80-753b-11eb-9166-291a026a813e.png) , please create a red button **#DD042B** in the menu for the version selection instead of being hidden in the top right corner
![image](https://user-images.githubusercontent.com/52718045/108794637-df4f4800-753a-11eb-8006-f7711336322f.png)

**Comment by alachambre** [comment]
Hello, 

I do not like your proposal. 

This documentation site embed the documentation of four projects, each one has its own versioning.  
The main toolbar is supposed to be global, so if the version is choosable from the toolbar then you must be able to choose the version of any component from there and not only the current one. 

The solution is to create drop-downs for each project, so you can select a project and then a version (same thing we have in the current docsite). 
We tried this solution first, we didn't like it, the result wasn't smooth at all.
We want a UI as clean as possible, to let the user focus on what matters: the content. 
So we went for a common design, used by many documentation sites: two ways to change the version, one on the top right corner and one on the bottom left corner. 
Here are some examples of other documentation sites that follow this pattern if you want to check: 

https://docs.antora.org/antora/2.3/
https://docs.fedoraproject.org/en-US/fedora/f30/
https://docs.asciidoctor.org/home/
https://isis.apache.org/docs/2.0.0-M4/about.html
