### ISSUE TITLE
Add possibility to switch from ☀️  to 🌑  theme

### ISSUE THREAD

**Issue by alachambre** [bonitasoft/bonitasoft.github.io#14]

**Comment by tbouffard** [comment]
@alachambre is this something mandatory or can we wait for having a 1st version of the site?

**Comment by alachambre** [comment]
You have the answer ^^ 
We created this ticket because it is really trendy atm, huge marketing value. And it is probably not a really hard job since it's only css. But it can indeed wait for a first version.

**Comment by tbouffard** [comment]
Ok, let's give it a try, if it is easy, let's do it while migrating. If more complex, do it letter.

**Comment by alachambre** [comment]
yes. 

We are going to give a try to https://tailwindcss.com/docs/dark-mode to define all the colors of the site, if it works as it's supposed to work then the dark theme will come freely.

**Comment by alachambre** [comment]
closed by  #106
