### ISSUE TITLE
No more results when searching in the bonita 2021.1 documentation 

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#147]
This seems related to the switch of bonita 7.12 to 2021.1
Docsearch indexes only the url related to the 7.12 version and still targets the gh-pages which doesn't provide redirect from 7.12 to 2021.1, so there is noting to crawl in this url and we don't crawl the urls related to the 2021.1 version

See #118 and #132
cc @alachambre @benjaminParisel

**Comment by tbouffard** [comment]
⚠️ The 2021.1 search is still ko
https://github.com/algolia/docsearch-configs/pull/3642/files hasn't replaced 7.12 by 2021.1

**Comment by alachambre** [comment]
Conf updated

https://github.com/algolia/docsearch-configs/compare/master...alachambre:patch-5

**Comment by tbouffard** [comment]
DocSearch configuration update has been merged: https://github.com/algolia/docsearch-configs/pull/3643

**Comment by tbouffard** [comment]
The search is now available in the live environment.
Thanks @alachambre
