### ISSUE TITLE
Change "Bonita ICI" menu option into "Labs"

### ISSUE THREAD

**Issue by NathalieC** [bonitasoft/bonitasoft.github.io#149]
![image](https://user-images.githubusercontent.com/10465851/109135468-67aa3480-7757-11eb-9328-a6edb15863fd.png)

The idea is to give more importance to the Labs project while fading the BICI glow.

### Additional Tasks 

The `labs` component replace the `bici` component token (https://github.com/bonitasoft/bonita-ici-doc/pull/127#issuecomment-786544130)

- [x] in the preview script, make the labs token available to create the preview of the `labs` component (see #176)
- [x] update the gh wf in the bici/labs documentation content repository (see https://github.com/bonitasoft/bonita-ici-doc/pull/127)
  - push content: identify itself as `labs`
  - preview: use the new labs token
- [x] update the redirect rules to make former `ici` and `bici` urls land to `labs/latest/bici` ones, see #32
  - waiting for https://github.com/bonitasoft/bonita-ici-doc/pull/128: urls are going to change with the introduction a dedicated bici Antora module
  - see #188
- [x] update the search configuration to use the new `labs` url, see https://github.com/algolia/docsearch-configs/pull/3691

Work will continue later with #175

**Comment by benjaminParisel** [comment]
It's only a content udpdate and it will be done by @NathalieC.

- [ ] From our part, we need to check if we want update redirect

**Comment by tbouffard** [comment]
All tasks done, so closing.
