### ISSUE TITLE
Generate one bundle for oldest version

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonitasoft.github.io#152]
- [x]  Generate and store one bundle per version in this repository

**Comment by tbouffard** [comment]
For this task, we can use the build-preview.bash script that is used for Documentation Content PR Preview: it is able to generate the documentation for a single component/branch ready for local file browsing (in particular, add html extension in url)

**Comment by benjaminParisel** [comment]
At this moment we get an [action](https://github.com/bonitasoft/bonitasoft.github.io/actions/workflows/generate-documentation.yml) to generate static content. 

An issue is created to manage bundle host https://github.com/bonitasoft/bonitasoft.github.io/issues/166
