### ISSUE TITLE
In taxonomy, link put on parent nodes, point to non existing page

### ISSUE THREAD

**Issue by baptistemesta** [bonitasoft/bonitasoft.github.io#181]
![Screenshot 2021-03-02 at 14 53 44](https://user-images.githubusercontent.com/2739234/109660387-150eb500-7b69-11eb-999c-257df06d6c54.png)

I guess it could be fixed only by removing the link to a non-existing page in the taxonomy, I can do that if you want. I just need to know in which branch

**Comment by benjaminParisel** [comment]
An issue is already open  https://github.com/bonitasoft/bonitasoft.github.io/issues/96. I close this issue ;)
