### ISSUE TITLE
Configure Google Analytics

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#30]
The Antora Default UI provide a way to include Google Analytics script in all pages by just adding a conf entry in the Antora Playbook, see https://docs.antora.org/antora/2.3/playbook/site-keys/#google-analytics-key

**Comment by uguy** [comment]
On D day change the repository secret named GOOGLE_ANALYTICS_KEY value with the one from marketing team.

**Comment by tbouffard** [comment]
I am going to close this issue as we have been able to configure Google Analytics.
I will create a dedicated issue to be managed just prior putting the site to production
