### ISSUE TITLE
Decide how we show out-of-support versions in the versions pick list

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#33]
In the current documentation site, out-of-support versions are in a submenu of the versions list of a component.

![image](https://user-images.githubusercontent.com/27200110/99986719-d4f0a700-2daf-11eb-98b2-3cad9f844318.png)

We don't have this by default with Antora UI but we also expect to be able to better identify pages related to out-of-support versions, see also #22.

We should decide if
- we keep the same display as in the old doc site
- we use the Antora default: all versions available without distinction, we can also renamed the displayed version to better identified it is out-of-support (see #22 proposal for instance, like `7.7 EOL`)
- we propose something else

**Comment by benjaminParisel** [comment]
From slack conversion: 
```
Nathalie Cotté  
Poorav est d'accord pour que le nouveau site de doc n'embarque que les versions de Bonita à partir de la 7.5
Par rapport aux .pdf des versions précédentes : il en faudrait un par version.
Je vais voir avec Delphine si le site de la Communauté peut les héberger. Et dans le nouveau site de doc, on ferait un lien vers cette page Community.
```

**Comment by alachambre** [comment]
Hello, 

We discussed about this issue a few days ago, we think that for all versions >= 7.3 (i.e all versions available in the previous documentation website), we should provide the documentation in HTML format (in a zip archive) and not in PDF. 

- Asciidoctor is made for HTML, you loose at least half of the properties in PDF (navigation, table of content, admonitions, exotic blocs ...)
- Provide an HTML zip archive for the documentation website is free for us: this is already the format we use to push it in production

**Comment by tbouffard** [comment]
We talked about removing 7.3 and 7.4 versions but we will still have to keep 7.5+ versions.
Today, only 7.9+ are supported versions, so we will still have 7.5 to 7.8 versions which are out of support

**Comment by alachambre** [comment]
Yes, but I guess that in the futur the 7.5 version will be removed and so on. 
It would be better to define a viable the strategy now for all removed versions.

**Comment by tbouffard** [comment]
Ok let's talk about it in person.?
My feeling is @alachambre and I agree that we don't want to customize the list of versions but we want to reduce the number of Bonita version we display on the website.
We definitvely have a topic about out-of-support versions
- #22 
- #116

**Comment by benjaminParisel** [comment]
We suggest to create a branch in bonita-doc repository to contains only one file with link to download oldest documentation. The target link should be the download link.

This solution allow us to use the default antora version.

On each release on Bonita plateform, we need to update this files to add the version unsupported.

**Comment by tbouffard** [comment]
Closing, there won't be any special things done for the version pick list.
We will display all versions hosted in the documentation and we will have a process to archive versions when a new one is released.
