### ISSUE TITLE
Decide how we redirect users to pre Bonita 7.3 documentation

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#34]
In the old documentation site, the Bonita 7.2 and before documentation version is displayed in the version pick list as shown in the above screenshot.

![image](https://user-images.githubusercontent.com/27200110/99986719-d4f0a700-2daf-11eb-98b2-3cad9f844318.png)

When clicking on such versions, a modal is displayed and the user is redirected to the Legacy documentation website 

![image](https://user-images.githubusercontent.com/27200110/99987386-b048ff00-2db0-11eb-9af8-394522429876.png)

We don't have this by default with Antora UI so we can
- reimplement the existing behaviour
- provide an alternative

See also #33.

**Antora Resources that may help**
- example that shows versions on the list (top bottom of the page) that point to external url: https://antora.gitlab.io/antora-ui-default/#some-code generated from https://gitlab.com/antora/antora-ui-default
- this repos doesn’t use external repositories for source as it doesn’t run antora cli to build the static site. It uses the https://gitlab.com/antora/antora-ui-default/-/blob/master/preview-src/ui-model.yml as config file and doc sources from the preview-src folder

**Comment by tbouffard** [comment]
The current decision is to 
- not reference the pre 7.3 documentation
- the pre 7.3 documentation will be decommissioned
- the documentation will be provided as an archive (details to precise)

**Comment by benjaminParisel** [comment]
This issues will be done in same time as #32
