### ISSUE TITLE
Check potential md to adoc conversion issue with tables

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#41]
During the initial BICI conversion (#17), we have detected that the tables in the rest api documentation were not correctly migrated, but those in the prerequisites page were correctly converted.
This may be an issue in the md sources: the rest api md files are generated, so maybe the syntax is not fully correct, the old generation system is able to convert them but not kramdoc.

So we have to be careful when doing conversion review for pages that contain tables.

**Comment by tbouffard** [comment]
Reopened, the  bonitasoft/bonita-ici-doc#121 contained a keyword that made the PR a linked PR, its merge triggered a wrong close of this issue.

**Comment by tbouffard** [comment]
Bonita documentation also has the issue
- 7.3: TODO provide link
- 7.5: https://github.com/bonitasoft/bonitasoft.github.io/pull/56#issuecomment-738868986

**Comment by tbouffard** [comment]
For rest api tables not migrated, the header separator is defined with `|:-|:-|` but some tables with such separators are correctly migrated.

For instance with Bonita 7.5
this is migrated
```
## Read a resource

| | |
|:-|:-|
| Request URL | `http://.../API/{API_name}/{resource_name}/{id} `| 
| Request Method | GET| 
| Response | an item in JSON| 
```

this is not migrated
```
## Create a resource
| | |
|:-|:-|
| Request URL | `http://.../API/{API_name}/{resource_name}/  `| 
| Request Method | POST| 
| Request Payload | an item in JSON| 
| Response | the same item in JSON, containing the values provided in the posted item, completed with default values and identifiers provided by Bonita BPM Engine.| 
```

**Possible root cause**: the issue may comes from a missing break line before the table

**Comment by benjaminParisel** [comment]
I confirm the missing break line before the table as root cause
