### ISSUE TITLE
Cleaning document content branches still using markdown

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#67]
Prior starting the real 'put the site live', the branches (except the ones related to product version - so feature branches) still using the markdown syntax must be managed.

There are a lot of old branches still alive. For instance, on 2021-01-13, there are 47 branches in bonita-doc (https://github.com/bonitasoft/bonita-doc/branches/all)
Some of them cannot be deleted for now, because there are considered as protected because of a branch pattern that is not restrictive enough (we only want to protect branches that exactly match product versions).

![image](https://user-images.githubusercontent.com/27200110/104447549-3b1dcd00-559c-11eb-9b66-20c259a99520.png)

For branches related to opened PR, we can ask people to merge them prior the migration. Otherwise, they will have to recreate them or migrate them manually.

**Comment by tbouffard** [comment]
All creators of the opened branches have been privately contacted on 2021-02-23: they are advised to remove the branches or create PR based on it.
Removal of remaining old branches will start after 2021-03-02

**Comment by benjaminParisel** [comment]
A mail was send by @tbouffard to all bonitasofter to ask them to manage/clean/merge theirs branches.

**Comment by tbouffard** [comment]
Reminder sent on 2021-03-01, obsolete branches will be removed starting from 2021-03-03

**Comment by tbouffard** [comment]
Obsolete branches have been removed on 2021-03-05. PR Authors have been asked to merged the opened Pull Requests prior the go to live, otherwise they will have to recreate or migrate them.
So closing.
