### ISSUE TITLE
Add a new variable available for doc content: `branding.version`

### ISSUE THREAD

**Issue by baptistemesta** [bonitasoft/bonitasoft.github.io#72]
We are missing in the current previous doc site a variable that hold the current branding version `2021.1`

But we still need the old `varVersion` that holds `7.12`

Thanks awesome team 🥂

**Comment by tbouffard** [comment]
We have a solution for this, see #54
This will be documented as part of #52

**Comment by baptistemesta** [comment]
It looks perfect ❤️  thanks

**Comment by benjaminParisel** [comment]
Already done and add documentation in contribution guide.  Enjoy !

**Comment by educhastenier** [comment]
Fixed in https://github.com/bonitasoft/bonita-doc/pull/1490
