### ISSUE TITLE
Custom 'danger bloc' are not converted into a proper asciidoctor admonition bloc

### ISSUE THREAD

**Issue by NathalieC** [bonitasoft/bonitasoft.github.io#77]
![image](https://user-images.githubusercontent.com/10465851/107524506-23932d80-6bb6-11eb-95b2-fa5e83c7fc8a.png)
should look like
![image](https://user-images.githubusercontent.com/10465851/107524559-3443a380-6bb6-11eb-9465-deba9f288340.png)

Current code is:
 danger
Both Windows and Mac have default security settings that will prevent execution of Bonita BPM. See below for further details about what you can do to bypass those security protections

It may be the same for info and warning.

At another point in the page, it displays nicely when current doc does not plan for a nice display:
![image](https://user-images.githubusercontent.com/10465851/107526355-0eb79980-6bb8-11eb-8e09-94acc2d168cb.png)
vs.
![image](https://user-images.githubusercontent.com/10465851/107526415-1f680f80-6bb8-11eb-9dbd-3c253a2f06e9.png)
The code that works is: 
WARNING: Oracle drivers have the same name but are different from one version to the other. Make sure you use the one that works with your Oracle Database version.

Now that I get it, I'm trying to fix it.

**Comment by tbouffard** [comment]
@NathalieC this is a known issue we have in a lot of pages
The conversion from the old custom 'note, warning, danger' is not fully managed and is documented here: https://github.com/bonitasoft/bonitasoft.github.io/blob/e642dae98a5c24ce2972c83df5a389d3edbd8026/docs/migrate-from-old-documentation-site/doc-content-conversion-for-new-doc-site.adoc#old-custom-tags-cleanup
We are looking for a better conversion solution.

**Comment by alachambre** [comment]
Hi, 

I updated the title of the issue tu point the generic problem. 
I'll add a migration step for custom danger bloc in the conversion script to fix this issue.
